global:
    scrape_interval: 2s
    evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          namespace: 'event-sourcing'
          app: 'ticketing-service'
