version: '3'

services:
  postgres:
    image: runcor3/webapp2_postgres:3.0
    container_name: postgres
    ports:
      - "5432:5432"

  ticketing-service:
    depends_on:
    - postgres

    image: runcor3/ticketing-service:latest
    container_name: ticketing-service
    ports:
      - "8080:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    environment:
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - "8888:8080"
    command: start-dev
